name: 'ace'
version: '1.0.0'

profile: 'ace'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ace:
    +materialized: table
    stg:
      strava: &strava
        +schema: strava
        +tags: ["strava"]
