apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  type: NodePort
  selector:
    app: weather-app
  ports:
    - name: producer-port
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: consumer-port
      protocol: TCP
      port: 8082
      targetPort: 8082
