name: Push Docker Image to ECR

on:
  push:
    branches:
      - main
  pull_request:

env:
  AWS_REGION: "ap-southeast-1"
  AWS_ACCOUNT_ID: "585233238792"

jobs:
  build:
    name: CD
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions-haojunsng-strava_pipeline
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: App Build and Push
        uses: docker/build-push-action@v4
        with:
          file: ./pipeline/pipeline/extract
          push: true
          tags: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ steps.login-ecr.outputs.registry }}
