name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pipeline

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Cache pre-commit hooks
      uses: actions/cache@v2
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.8.2
    - name: Install dependencies
      run: |
        poetry install && source $(poetry env info --path)/bin/activate
    - name: Run pre-commit
      run: |
        pre-commit run --all-files
    - name: Run tests for DAGs
      run: |
        cd pipeline/orchestration/dags
        python tests/dag_integrity.py
